#!/bin/bash
set -e

cd "$(dirname "$0")"

AD9361_URI="${1:-ip:192.168.1.10}"
RX_GAIN="${JAMSYSTEM_RX_GAIN_DB:-45}"

pkill -9 -f "ad9361_rk3588|predict_single.py|fast_rx_rknn" 2>/dev/null || true

echo "[SPEED] uri=${AD9361_URI}"
echo "[SPEED] rx_gain=${RX_GAIN}"
echo "[SPEED] mode=cpp_fast_rknn stft_stride=${JAMSYSTEM_FAST_STFT_STRIDE:-2}"
echo "[SPEED] fast_refine_narrowband=${JAMSYSTEM_FAST_REFINE_NARROWBAND:-0}"

if [ -x ./fast_rx_rknn ]; then
  JAMSYSTEM_ENABLE_NO_SIGNAL_GATE=0 \
  JAMSYSTEM_FAST_STFT_STRIDE="${JAMSYSTEM_FAST_STFT_STRIDE:-2}" \
  JAMSYSTEM_FAST_REFINE_NARROWBAND="${JAMSYSTEM_FAST_REFINE_NARROWBAND:-0}" \
  JAMSYSTEM_RX_GAIN_DB="${RX_GAIN}" \
  ./fast_rx_rknn "${AD9361_URI}"
  exit $?
fi

echo "[SPEED] fast_rx_rknn not found; fallback to ad9361_rk3588 worker path"

JAMSYSTEM_CLASSIFY_SUBTRACT_QPSK_REF=0 \
JAMSYSTEM_ENABLE_OVERLAP_WINDOW=0 \
JAMSYSTEM_ENABLE_NO_SIGNAL_GATE=0 \
JAMSYSTEM_DISABLE_RECORD=1 \
JAMSYSTEM_DISABLE_PLOT_EXPORT=1 \
JAMSYSTEM_FAST_TEST_MODE=1 \
JAMSYSTEM_FAST_CLASSIFY_ONLY=1 \
JAMSYSTEM_FAST_RESTORE=1 \
JAMSYSTEM_FAST_SKIP_REFERENCE_METRICS=1 \
JAMSYSTEM_FAST_REFINE_NARROWBAND="${JAMSYSTEM_FAST_REFINE_NARROWBAND:-0}" \
JAMSYSTEM_ENABLE_TRUE_BER=0 \
JAMSYSTEM_USE_PY_WORKER=1 \
JAMSYSTEM_CAPTURED_FILE=/dev/shm/jamsystem_captured.bin \
JAMSYSTEM_RX_GAIN_DB="${RX_GAIN}" \
./ad9361_rk3588 rx_unknown "${AD9361_URI}" digital_qpsk rx_only
